### ISSUE TITLE
npm install reliable-macaca-slave -g exit with "Failed at the zmq@2.13.0 install script 'node-gyp rebuild'."

### ISSUE THREAD

**Issue by davidli2017** [reliablejs/reliable-macaca-slave#23]
gyp: Call to 'pkg-config libzmq --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/reliable-macaca-slave/node_modules/zmq
gyp ERR! node -v v4.4.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "reliable-macaca-slave" "-g"
npm ERR! node v4.4.6
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.13.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.13.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq

这个问题是 使用了不恰当的gyp  版本build，还说，zmq版本不对
mac: 10.11.5
node:4.4.6

**Comment by davidli2017** [comment]
fixed
在Mac 下必须先安装zmq 
brew install zmq

**Comment by wangyunshuai** [comment]
始终安装不成功, 怎么办? 手动下载也不成功, 迅雷也试了...
```
➜  ~ brew install zeromq
==> Downloading http://download.zeromq.org/zeromq-4.0.5.tar.gz
######################################################################## 100.0%
curl: (7) Failed to connect to archive.org port 443: Operation timed out
Error: Failed to download resource "zeromq"
Download failed: http://download.zeromq.org/zeromq-4.0.5.tar.gz
```
